server:
  port: 7073
spring:
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.java.service.impl
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: yuan
    password: yuan123!@#
    mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.java.pojo

